### ISSUE TITLE
Error: Cannot find module 'node_modules/@cucumber/pretty-formatter'

### ISSUE THREAD

**Issue by satabdisikdar** [cucumber/cucumber-js-pretty-formatter#3]
I see this error and also `Require stack:- /home/abc/Documents/xyz/FY_web_test/web/test/index.js`. 
Dependencies versions:
```
"@cucumber/cucumber": "^7.2.1",
"cucumber-html-reporter": "^5.4.0",
"@cucumber/pretty-formatter": "latest",
```

**Comment by satabdisikdar** [comment]
cc: @jbpros @kozhevnikov

**Comment by kozhevnikov** [comment]
npm isn't Maven, `latest` is not a valid version value, re-install it. If updating versions becomes a burden on a big project, you can use ncu tool.

https://www.npmjs.com/package/npm-check-updates
