### ISSUE TITLE
Hook name does not appear in the console alongside the step names

### ISSUE THREAD

**Issue by aleksdobrev** [cucumber/cucumber-js-pretty-formatter#52]
### 👓 What did you see?

I have a before hook with a "name", but I don't see the name printed in the console after the scenario is executed. Not sure if its an issue or if I need to configure something more.
The hooks and the test are executed without errors.

```
Before({ name: 'Before hook name' }, async function () {
  this.context = await browser.newContext()
  this.page = await this.context.newPage()
})
```

### ✅ What did you expect to see?

I expect the name the be printed in the console when the test is executed.
I use the `--format @cucumber/pretty-formatter` formatter.

Should I use another one?

### 📦 Which tool/library version are you using?

Here are the tools I am using.

```
"devDependencies": {
    "@cucumber/cucumber": "^10.0.0",
    "@cucumber/html-formatter": "^20.4.0",
    "@cucumber/messages": "^22.0.0",
    "@cucumber/pretty-formatter": "^1.0.0",
    "@playwright/test": "^1.39.0",
    "@types/node": "^20.8.4",
    "cucumber-html-reporter": "^7.1.1",
    "playwright": "^1.39.0",
    "ts-node": "^10.9.1",
    "typescript": "^5.2.2"
    },
```

**Comment by davidjgoss** [comment]
The pretty formatter doesn't yet support outputting the hook names - I'll transfer this issue there.

**Comment by aleksdobrev** [comment]
Ok :) 
Is there any other formatter that you know of that supports that? 
I couldn't find one in the documentation. Tried with the `--format summary` and  `--format progress-bar` but it did not work either.

**Comment by davidjgoss** [comment]
To clarify @aleksdobrev, with Cucumber console formatters hooks are only normally printed if they have failed - otherwise it's just steps that are reported. Are you seeing the name missing for failures in the `summary` or `progress-bar` formatters?

**Comment by aleksdobrev** [comment]
@davidjgoss thanks for the clarification.
I've checked and can confirm that on failure I can see the hook name when using the `summary`, or `progress-bar` formatters and also when using the `pretty-formatter`.

**Comment by davidjgoss** [comment]
Great, thanks. I'm going to close this then - showing hooks all the time is not something we'd do in any of our first-party console formatters, although you could always write a custom one to suit your needs.
