### ISSUE TITLE
How to set theme without removing default settings?

### ISSUE THREAD

**Issue by emfomy** [cucumber/cucumber-js-pretty-formatter#6]
**Is your feature request related to a problem? Please describe.**
I want to change the color of a keyword.
However, by setting `--format-options '{"theme": { "step text": "magenta" } }'`, it removes all the other colors.

**Describe the solution you'd like**
Add an option to preserve default colors.

**Describe alternatives you've considered**
Or provide the default theme in the documentation for reference.

**Comment by davidjgoss** [comment]
@emfomy thanks for raising.

Do you manage your cucumber config in [a `cucumber.js` file](https://github.com/cucumber/cucumber-js/blob/main/docs/configuration.md#files) or similar?

I'm wondering if we could expose the default theme as an export from here, and thus enable something like this:

```
const { DEFAULT_THEME } = require('@cucumber/pretty-formatter')

module.exports = {
  someprofile: {
    formatOptions: {
      theme: {
        ...DEFAULT_THEME,
        'step text': 'magenta'
      }
    }
  }
}
```

**Comment by emfomy** [comment]
I'm using a `cucumber.js` file to manage my config.

It'll be great to have the default theme exported.
