### ISSUE TITLE
Error: cannot find module `../node_modules/@cucumber/cucumber/lib/formatter/helper.js`

### ISSUE THREAD

**Issue by kiranparajuli589** [cucumber/cucumber-js-pretty-formatter#9]
**Describe the bug**
The latest version of the `cucumber formatter` does not work with the latest version of the `cucumber-js`.

**To Reproduce**
1. Install the latest version of cucumber and cucumber formatter
```json
{
  "scripts": {
    "test:e2e": "cucumber-js --require cucumber.conf.js --require tests/acceptance/stepDefinitions -f @cucumber/pretty-formatter"
   },
  "devDependencies": {
    "@cucumber/cucumber": "^8.0.0-rc.1",
    "@cucumber/pretty-formatter": "^1.0.0-alpha.1",
  }
}
```

**Expected behavior**
The tests should execute without any exception

**Screenshots**
![Screenshot from 2021-12-13 10-13-42](https://user-images.githubusercontent.com/39373750/145752585-35858e11-871a-468c-8c86-f19ffd5bee8f.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS (focal)
 - Browser: was not required for this case
 - Version: `1.0.0-alpha.1`

**Comment by Nielsvd94** [comment]
Is there a plan to fix this issue? The plugin is currently unusable for versions 7 and up

**Comment by pk** [comment]
I had same problems with the package on the 8.0.0-rc.2 but when I switched my project to ESM I can use the pretty formatter without any problems.
